name: my_social_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  equatable: ^1.2.0
  google_sign_in: ^4.5.1
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.6
  google_fonts: ^1.1.0
  flutter_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
